name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Node setup info
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Cloning the repo
      run: |
        git clone https://github.com/pkpndy/WebApp-cicd.git
        cd WebApp-cicd

    - name: Install dependencies
      run: |
        npm install

    - name: Validate and Create Build Artifact
      run: |
        npx html-validate index.html  
        npx stylelint "**/*.css"

        if [ $? -eq 0 ]; then
          echo "Tests passed. Creating a build artifact..."
          zip -r my-web-app.zip . -x "node_modules/*"
        else
          echo "Tests failed. Build artifact creation skipped."
          exit 1
        fi

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Web Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}  

    - name: Executing deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt-get -y update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx
          cd home
          sudo mv * /var/www/html